name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Log in to Railway
        run: railway login

      - name: Deploy to Railway
        run: railway up
